version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  wuzzah:
    image: wuzzah/wuzzah:latest
    container_name: wuzzah
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: your_db
      DB_USER: your_user
      DB_PASS: your_password
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  ossec:
    image: ossec/ossec-hids:latest
    container_name: ossec
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: your_db
      DB_USER: your_user
      DB_PASS: your_password
    depends_on:
      - postgres
    volumes:
      - ossec_data:/var/ossec/data
    ports:
      - "1514:1514"

  the_hive:
    image: thehiveproject/thehive:latest
    container_name: the_hive
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: your_db
      DB_USER: your_user
      DB_PASS: your_password
    depends_on:
      - postgres
    volumes:
      - the_hive_data:/opt/thehive/data
    ports:
      - "9000:9000"

  rsyslog:
    image: adubkov/rsyslog
    container_name: rsyslog
    volumes:
      - rsyslog_config:/etc/rsyslog.d
      - rsyslog_data:/var/log/syslog
    ports:
      - "514:514/udp"
      - "514:514/tcp"
    depends_on:
      - postgres
    environment:
      RSYSLOG_OMSQL_HOST: postgres
      RSYSLOG_OMSQL_PORT: 5432
      RSYSLOG_OMSQL_DATABASE: your_db
      RSYSLOG_OMSQL_USER: your_user
      RSYSLOG_OMSQL_PASSWORD: your_password

volumes:
  postgres_data:
  ossec_data:
  the_hive_data:
  rsyslog_config:
  rsyslog_data:
