version: '3.8'

services:
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    command: -i 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
